export const dietaryRestrictions = [
  { value: 'gluten-free', label: 'Gluten-Free' },
  { value: 'lactose-free', label: 'Lactose-Free' },
  { value: 'low-sodium', label: 'Low-Sodium' },
  { value: 'low-fodmap', label: 'Low-FODMAP' },
  { value: 'nut-free', label: 'Nut-Free' },
  { value: 'sugar-free', label: 'Sugar-Free' },
  { value: 'low-carb', label: 'Low-Carb' },
  { value: 'diabetic-friendly', label: 'Diabetic-Friendly' },
  { value: 'low-cholesterol', label: 'Low-Cholesterol' },
  { value: 'allergen-free', label: 'Allergen-Free' },
  { value: 'vegetarian', label: 'Vegetarian' },
  { value: 'vegan', label: 'Vegan' },
  { value: 'pescatarian', label: 'Pescatarian' },
  { value: 'flexitarian', label: 'Flexitarian' },
  { value: 'plant-based', label: 'Plant-Based' },
  { value: 'kosher', label: 'Kosher' },
  { value: 'halal', label: 'Halal' },
  { value: 'hindu', label: 'Hindu' },
  { value: 'buddhist', label: 'Buddhist' },
  { value: 'keto', label: 'Keto (Ketogenic)' },
  { value: 'paleo', label: 'Paleo' },
  { value: 'whole30', label: 'Whole30' },
  { value: 'raw-food', label: 'Raw Food' },
  { value: 'organic', label: 'Organic' },
  { value: 'macrobiotic', label: 'Macrobiotic' }
];
